git clone https://android.googlesource.com/accessories/manifest	
git clone https://android.googlesource.com/device/asus/deb	
git clone https://android.googlesource.com/device/asus/flo	
git clone https://android.googlesource.com/device/asus/flo-kernel	
git clone https://android.googlesource.com/device/asus/fugu	
git clone https://android.googlesource.com/device/asus/fugu-kernel
git clone https://android.googlesource.com/device/asus/grouper
git clone https://android.googlesource.com/device/asus/tilapia	
git clone https://android.googlesource.com/device/common	
git clone https://android.googlesource.com/device/generic/arm64	
git clone https://android.googlesource.com/device/generic/armv7-a	
git clone https://android.googlesource.com/device/generic/armv7-a-neon	
git clone https://android.googlesource.com/device/generic/art	
git clone https://android.googlesource.com/device/generic/common	
git clone https://android.googlesource.com/device/generic/goldfish	
git clone https://android.googlesource.com/device/generic/mini-emulator-arm64	
git clone https://android.googlesource.com/device/generic/mini-emulator-armv7-a-neon	
git clone https://android.googlesource.com/device/generic/mini-emulator-mips	
git clone https://android.googlesource.com/device/generic/mini-emulator-x86	
git clone https://android.googlesource.com/device/generic/mini-emulator-x86_64	
git clone https://android.googlesource.com/device/generic/mips	
git clone https://android.googlesource.com/device/generic/qemu	
git clone https://android.googlesource.com/device/generic/x86	
git clone https://android.googlesource.com/device/generic/x86_64	
git clone https://android.googlesource.com/device/google/accessory/adk2012	
git clone https://android.googlesource.com/device/google/accessory/adk2012_demo
git clone https://android.googlesource.com/device/google/accessory/arduino	
git clone https://android.googlesource.com/device/google/accessory/demokit
git clone https://android.googlesource.com/device/google/atv
git clone https://android.googlesource.com/device/google/debugcable
git clone https://android.googlesource.com/device/google/phantasm	
git clone https://android.googlesource.com/device/htc/common
git clone https://android.googlesource.com/device/htc/dream
git clone https://android.googlesource.com/device/htc/dream-sapphire	
git clone https://android.googlesource.com/device/htc/flounder	
git clone https://android.googlesource.com/device/htc/flounder-kernel	
git clone https://android.googlesource.com/device/htc/passion	
git clone https://android.googlesource.com/device/htc/passion-common
git clone https://android.googlesource.com/device/htc/sapphire
git clone https://android.googlesource.com/device/lge/hammerhead	
git clone https://android.googlesource.com/device/lge/hammerhead-kernel	
git clone https://android.googlesource.com/device/lge/mako	
git clone https://android.googlesource.com/device/lge/mako-kernel	
git clone https://android.googlesource.com/device/moto/common	
git clone https://android.googlesource.com/device/moto/shamu	
git clone https://android.googlesource.com/device/moto/shamu-kernel	
git clone https://android.googlesource.com/device/moto/stingray	
git clone https://android.googlesource.com/device/moto/wingray	
git clone https://android.googlesource.com/device/sample	
git clone https://android.googlesource.com/device/samsung_slsi/arndale	
git clone https://android.googlesource.com/device/samsung/crespo	
git clone https://android.googlesource.com/a.k.a. 
git clone https://android.googlesource.com/device/samsung/crespo4g	
git clone https://android.googlesource.com/a.k.a. 
git clone https://android.googlesource.com/device/samsung/maguro	
git clone https://android.googlesource.com/device/samsung/manta	
git clone https://android.googlesource.com/device/samsung/toro	
git clone https://android.googlesource.com/device/samsung/toroplus	
git clone https://android.googlesource.com/Galaxy 
git clone https://android.googlesource.com/device/samsung/torospr	
git clone https://android.googlesource.com/device/samsung/tuna	
git clone https://android.googlesource.com/device/sony/lt26	
git clone https://android.googlesource.com/device/ti/bootloader/uboot	
git clone https://android.googlesource.com/device/ti/panda	
git clone https://android.googlesource.com/kernel/bcm	
git clone https://android.googlesource.com/kernel/common	
git clone https://android.googlesource.com/kernel/exynos	
git clone https://android.googlesource.com/kernel/goldfish	
git clone https://android.googlesource.com/kernel/lk	
git clone https://android.googlesource.com/kernel/mediatek	
git clone https://android.googlesource.com/kernel/msm	
git clone https://android.googlesource.com/kernel/omap	
git clone https://android.googlesource.com/kernel/samsung	
git clone https://android.googlesource.com/kernel/tegra	
git clone https://android.googlesource.com/kernel/x86_64	
git clone https://android.googlesource.com/Kernel-Projects	
git clone https://android.googlesource.com/mirror/manifest	
git clone https://android.googlesource.com/hosted 
git clone https://android.googlesource.com/platform/abi/cpp	
git clone https://android.googlesource.com/platform/art	
git clone https://android.googlesource.com/platform/bionic	
git clone https://android.googlesource.com/platform/bootable/bootloader/legacy	#bootloader reference code
git clone https://android.googlesource.com/platform/bootable/diskinstaller	
git clone https://android.googlesource.com/platform/bootable/recovery	
git clone https://android.googlesource.com/platform/build	#build system
git clone https://android.googlesource.com/platform/build/blueprint	
git clone https://android.googlesource.com/platform/build/soong	
git clone https://android.googlesource.com/platform/cts	#Compatibility Test Suite
git clone https://android.googlesource.com/platform/dalvik	#Dalvik virtual machine and core libraries
git clone https://android.googlesource.com/platform/dalvik2	
git clone https://android.googlesource.com/platform/dalvik-snapshot	
git clone https://android.googlesource.com/platform/developers/build	
git clone https://android.googlesource.com/platform/developers/demos	
git clone https://android.googlesource.com/platform/developers/docs	
git clone https://android.googlesource.com/platform/developers/samples/android	
git clone https://android.googlesource.com/platform/development	#Platform engineering tools, sample code
git clone https://android.googlesource.com/platform/docs/source.android.com	#Source files for the
git clone https://android.googlesource.com/platform/external/aac	
git clone https://android.googlesource.com/platform/external/actionbarsherlock	
git clone https://android.googlesource.com/platform/external/aes	
git clone https://android.googlesource.com/platform/external/alac	
git clone https://android.googlesource.com/platform/external/android-clat	
git clone https://android.googlesource.com/platform/external/android-mock	
git clone https://android.googlesource.com/platform/external/ant-glob	
git clone https://android.googlesource.com/platform/external/antlr	
git clone https://android.googlesource.com/platform/external/apache-apr	
git clone https://android.googlesource.com/platform/external/apache-apr-util	
git clone https://android.googlesource.com/platform/external/apache-harmony	
git clone https://android.googlesource.com/platform/external/apache-http	
git clone https://android.googlesource.com/platform/external/apache-log4cxx	
git clone https://android.googlesource.com/platform/external/apache-qp	#Quoted-printable library
git clone https://android.googlesource.com/platform/external/apache-xml	
git clone https://android.googlesource.com/platform/external/apple-coreaudiosamples	
git clone https://android.googlesource.com/platform/external/arduino	
git clone https://android.googlesource.com/platform/external/arduino-ide	
git clone https://android.googlesource.com/platform/external/astl	
git clone https://android.googlesource.com/platform/external/bison	
git clone https://android.googlesource.com/platform/external/blktrace	
git clone https://android.googlesource.com/platform/external/bluetooth/bluedroid	
git clone https://android.googlesource.com/platform/external/bluetooth/bluez	
git clone https://android.googlesource.com/platform/external/bluetooth/glib	
git clone https://android.googlesource.com/platform/external/bluetooth/hcidump	
git clone https://android.googlesource.com/platform/external/bluez	
git clone https://android.googlesource.com/platform/external/boost	
git clone https://android.googlesource.com/platform/external/boringssl	
git clone https://android.googlesource.com/platform/external/bouncycastle	
git clone https://android.googlesource.com/platform/external/bsdiff	
git clone https://android.googlesource.com/platform/external/bzip2	
git clone https://android.googlesource.com/platform/external/cblas	
git clone https://android.googlesource.com/platform/external/ceres-solver	
git clone https://android.googlesource.com/platform/external/checkpolicy	
git clone https://android.googlesource.com/platform/external/cherry	
git clone https://android.googlesource.com/platform/external/chromium	
git clone https://android.googlesource.com/platform/external/chromium_org	
git clone https://android.googlesource.com/platform/external/chromium_org/sdch/open-vcdiff	
git clone https://android.googlesource.com/platform/external/chromium_org/testing/gtest	
git clone https://android.googlesource.com/platform/external/chromium_org/third_party/angle	
git clone https://android.googlesource.com/platform/external/chromium_org/third_party/angle_dx11	
git clone https://android.googlesource.com/platform/external/chromium_org/third_party/boringssl/src	
git clone https://android.googlesource.com/platform/external/chromium_org/third_party/brotli/src	
git clone https://android.googlesource.com/platform/external/chromium_org/third_party/eyesfree/src/android/java/src/com/googlecode/eyesfree/braille	
git clone https://android.googlesource.com/platform/external/chromium_org/third_party/freetype	
git clone https://android.googlesource.com/platform/external/chromium_org/third_party/icu	
git clone https://android.googlesource.com/platform/external/chromium_org/third_party/leveldatabase/src	
git clone https://android.googlesource.com/platform/external/chromium_org/third_party/libaddressinput/src	
git clone https://android.googlesource.com/platform/external/chromium_org/third_party/libjingle/source/talk	
git clone https://android.googlesource.com/platform/external/chromium_org/third_party/libjpeg_turbo	
git clone https://android.googlesource.com/platform/external/chromium_org/third_party/libphonenumber/src/phonenumbers	
git clone https://android.googlesource.com/platform/external/chromium_org/third_party/libphonenumber/src/resources	
git clone https://android.googlesource.com/platform/external/chromium_org/third_party/libsrtp	
git clone https://android.googlesource.com/platform/external/chromium_org/third_party/libvpx	
git clone https://android.googlesource.com/platform/external/chromium_org/third_party/libyuv	
git clone https://android.googlesource.com/platform/external/chromium_org/third_party/mesa/src	
git clone https://android.googlesource.com/platform/external/chromium_org/third_party/openmax_dl	
git clone https://android.googlesource.com/platform/external/chromium_org/third_party/openssl	
git clone https://android.googlesource.com/platform/external/chromium_org/third_party/opus/src	
git clone https://android.googlesource.com/platform/external/chromium_org/third_party/ots	
git clone https://android.googlesource.com/platform/external/chromium_org/third_party/sfntly/cpp/src	
git clone https://android.googlesource.com/platform/external/chromium_org/third_party/skia	
git clone https://android.googlesource.com/platform/external/chromium_org/third_party/skia/gyp	
git clone https://android.googlesource.com/platform/external/chromium_org/third_party/skia/include	
git clone https://android.googlesource.com/platform/external/chromium_org/third_party/skia/src	
git clone https://android.googlesource.com/platform/external/chromium_org/third_party/smhasher/src	
git clone https://android.googlesource.com/platform/external/chromium_org/third_party/usrsctp/usrsctplib	
git clone https://android.googlesource.com/platform/external/chromium_org/third_party/WebKit	
git clone https://android.googlesource.com/platform/external/chromium_org/third_party/webrtc	
git clone https://android.googlesource.com/platform/external/chromium_org/third_party/yasm/source/patched-yasm	
git clone https://android.googlesource.com/platform/external/chromium_org/tools/grit	
git clone https://android.googlesource.com/platform/external/chromium_org/tools/gyp	
git clone https://android.googlesource.com/platform/external/chromium_org/v8	
git clone https://android.googlesource.com/platform/external/chromium-libpac	
git clone https://android.googlesource.com/platform/external/chromium-trace	
git clone https://android.googlesource.com/platform/external/cibu-fonts	
git clone https://android.googlesource.com/platform/external/clang	
git clone https://android.googlesource.com/platform/external/clang_35a	
git clone https://android.googlesource.com/platform/external/clearsilver	
git clone https://android.googlesource.com/platform/external/cmockery	
git clone https://android.googlesource.com/platform/external/codesourcery	
git clone https://android.googlesource.com/platform/external/collada	
git clone https://android.googlesource.com/platform/external/compiler-rt	
git clone https://android.googlesource.com/platform/external/compiler-rt_35a	
git clone https://android.googlesource.com/platform/external/conscrypt	
git clone https://android.googlesource.com/platform/external/curl	
git clone https://android.googlesource.com/platform/external/dbus	
git clone https://android.googlesource.com/platform/external/deqp	
git clone https://android.googlesource.com/platform/external/dexmaker	
git clone https://android.googlesource.com/platform/external/dhcpcd	
git clone https://android.googlesource.com/platform/external/dnsmasq	
git clone https://android.googlesource.com/platform/external/doclava	
git clone https://android.googlesource.com/platform/external/dosfstools	
git clone https://android.googlesource.com/platform/external/droiddriver	
git clone https://android.googlesource.com/platform/external/dropbear	
git clone https://android.googlesource.com/platform/external/e2fsprogs	
git clone https://android.googlesource.com/platform/external/easymock	
git clone https://android.googlesource.com/platform/external/eclipse-basebuilder	
git clone https://android.googlesource.com/platform/external/eclipse-windowbuilder	
git clone https://android.googlesource.com/platform/external/eglib	
git clone https://android.googlesource.com/platform/external/eigen	
git clone https://android.googlesource.com/platform/external/elfcopy	
git clone https://android.googlesource.com/platform/external/elfutils	
git clone https://android.googlesource.com/platform/external/embunit	
git clone https://android.googlesource.com/platform/external/emma	
git clone https://android.googlesource.com/platform/external/esd	
git clone https://android.googlesource.com/platform/external/expat	
git clone https://android.googlesource.com/platform/external/eyes-free	
git clone https://android.googlesource.com/platform/external/f2fs-tools	
git clone https://android.googlesource.com/platform/external/faad	
git clone https://android.googlesource.com/platform/external/fat32lib	
git clone https://android.googlesource.com/platform/external/fdlibm	
git clone https://android.googlesource.com/platform/external/fio	
git clone https://android.googlesource.com/platform/external/flac	
git clone https://android.googlesource.com/platform/external/fonttools	
git clone https://android.googlesource.com/platform/external/free-image	
git clone https://android.googlesource.com/platform/external/freetype	
git clone https://android.googlesource.com/platform/external/fsck_msdos	
git clone https://android.googlesource.com/platform/external/ganymed-ssh2	
git clone https://android.googlesource.com/platform/external/gcc-demangle	
git clone https://android.googlesource.com/platform/external/gdata	
git clone https://android.googlesource.com/platform/external/genext2fs	
git clone https://android.googlesource.com/platform/external/giflib	
git clone https://android.googlesource.com/platform/external/glide	
git clone https://android.googlesource.com/platform/external/gmock	
git clone https://android.googlesource.com/platform/external/googleclient	
git clone https://android.googlesource.com/platform/external/google-diff-match-patch	
git clone https://android.googlesource.com/platform/external/google-fonts/carrois-gothic-sc	
git clone https://android.googlesource.com/platform/external/google-fonts/coming-soon	
git clone https://android.googlesource.com/platform/external/google-fonts/cutive-mono	
git clone https://android.googlesource.com/platform/external/google-fonts/dancing-script	
git clone https://android.googlesource.com/platform/external/google-tv-pairing-protocol	
git clone https://android.googlesource.com/platform/external/grub	
git clone https://android.googlesource.com/platform/external/gsoap	
git clone https://android.googlesource.com/platform/external/gtest	
git clone https://android.googlesource.com/platform/external/guava	
git clone https://android.googlesource.com/platform/external/hamcrest	
git clone https://android.googlesource.com/platform/external/harfbuzz	
git clone https://android.googlesource.com/platform/external/harfbuzz_ng	
git clone https://android.googlesource.com/platform/external/hcidump	
git clone https://android.googlesource.com/platform/external/hsqldb	
git clone https://android.googlesource.com/platform/external/hyphenation	
git clone https://android.googlesource.com/platform/external/icu	
git clone https://android.googlesource.com/platform/external/icu4c	
git clone https://android.googlesource.com/platform/external/id3lib	
git clone https://android.googlesource.com/platform/external/iproute2	
git clone https://android.googlesource.com/platform/external/ipsec-tools	
git clone https://android.googlesource.com/platform/external/iptables	
git clone https://android.googlesource.com/platform/external/iputils	
git clone https://android.googlesource.com/platform/external/jack	
git clone https://android.googlesource.com/platform/external/jarjar	
git clone https://android.googlesource.com/platform/external/javasqlite	
git clone https://android.googlesource.com/platform/external/javassist	
git clone https://android.googlesource.com/platform/external/jdiff	
git clone https://android.googlesource.com/platform/external/jemalloc	
git clone https://android.googlesource.com/platform/external/jenkins-hash	
git clone https://android.googlesource.com/platform/external/jhead	
git clone https://android.googlesource.com/platform/external/jline	
git clone https://android.googlesource.com/platform/external/jmdns	
git clone https://android.googlesource.com/platform/external/jmonkeyengine	
git clone https://android.googlesource.com/platform/external/jpeg	
git clone https://android.googlesource.com/platform/external/jsilver	
git clone https://android.googlesource.com/platform/external/jsmn	
git clone https://android.googlesource.com/platform/external/jsoncpp	
git clone https://android.googlesource.com/platform/external/jsr305	
git clone https://android.googlesource.com/platform/external/junit	
git clone https://android.googlesource.com/platform/external/kernel-headers	
git clone https://android.googlesource.com/platform/external/ksoap2	
git clone https://android.googlesource.com/platform/external/lame	
git clone https://android.googlesource.com/platform/external/lcc	
git clone https://android.googlesource.com/platform/external/libavc	
git clone https://android.googlesource.com/platform/external/libcap-ng	
git clone https://android.googlesource.com/platform/external/libcxx	
git clone https://android.googlesource.com/platform/external/libcxx_35a	
git clone https://android.googlesource.com/platform/external/libcxxabi	
git clone https://android.googlesource.com/platform/external/libcxxabi_35a	
git clone https://android.googlesource.com/platform/external/libcxxrt	
git clone https://android.googlesource.com/platform/external/libedit	
git clone https://android.googlesource.com/platform/external/libexif	
git clone https://android.googlesource.com/platform/external/libffi	
git clone https://android.googlesource.com/platform/external/libgsm	
git clone https://android.googlesource.com/platform/external/libhevc	
git clone https://android.googlesource.com/platform/external/liblzf	
git clone https://android.googlesource.com/platform/external/libmpeg2	
git clone https://android.googlesource.com/platform/external/libmtp	
git clone https://android.googlesource.com/platform/external/libnfc-nci	
git clone https://android.googlesource.com/platform/external/libnfc-nxp	
git clone https://android.googlesource.com/platform/external/libnl	
git clone https://android.googlesource.com/platform/external/libnl-headers	
git clone https://android.googlesource.com/platform/external/libogg	
git clone https://android.googlesource.com/platform/external/libopus	
git clone https://android.googlesource.com/platform/external/libpcap	
git clone https://android.googlesource.com/platform/external/libphonenumber	
git clone https://android.googlesource.com/platform/external/libpng	
git clone https://android.googlesource.com/platform/external/libppp	
git clone https://android.googlesource.com/platform/external/libseccomp-helper	
git clone https://android.googlesource.com/platform/external/libselinux	
git clone https://android.googlesource.com/platform/external/libsepol	
git clone https://android.googlesource.com/platform/external/libssh2	
git clone https://android.googlesource.com/platform/external/libunwind	
git clone https://android.googlesource.com/platform/external/libusb	
git clone https://android.googlesource.com/platform/external/libusb_aah	
git clone https://android.googlesource.com/platform/external/libusb-compat	
git clone https://android.googlesource.com/platform/external/libutf	
git clone https://android.googlesource.com/platform/external/libvorbis	
git clone https://android.googlesource.com/platform/external/libvpx	
git clone https://android.googlesource.com/platform/external/libvterm	
git clone https://android.googlesource.com/platform/external/libxml2	
git clone https://android.googlesource.com/platform/external/libxslt	
git clone https://android.googlesource.com/platform/external/libyuv	
git clone https://android.googlesource.com/platform/external/linux-tools-perf	
git clone https://android.googlesource.com/platform/external/littlemock	
git clone https://android.googlesource.com/platform/external/lld	
git clone https://android.googlesource.com/platform/external/lldb	#Not yet needed
git clone https://android.googlesource.com/platform/external/lldb-utils	
git clone https://android.googlesource.com/platform/external/llvm	
git clone https://android.googlesource.com/platform/external/llvm_35a	
git clone https://android.googlesource.com/platform/external/login-items-ae	
git clone https://android.googlesource.com/platform/external/lohit-fonts	
git clone https://android.googlesource.com/platform/external/ltrace	
git clone https://android.googlesource.com/platform/external/lz4	
git clone https://android.googlesource.com/platform/external/lzma	
git clone https://android.googlesource.com/platform/external/marisa-trie	
git clone https://android.googlesource.com/platform/external/markdown	
git clone https://android.googlesource.com/platform/external/mdnsresponder	
git clone https://android.googlesource.com/platform/external/mesa3d	
git clone https://android.googlesource.com/platform/external/messageformat	
git clone https://android.googlesource.com/platform/external/mksh	
git clone https://android.googlesource.com/platform/external/mockftpserver	
git clone https://android.googlesource.com/platform/external/mockito	
git clone https://android.googlesource.com/platform/external/mockwebserver	
git clone https://android.googlesource.com/platform/external/mp4parser	
git clone https://android.googlesource.com/platform/external/mp4v2	
git clone https://android.googlesource.com/platform/external/mpg123	
git clone https://android.googlesource.com/platform/external/mtpd	
git clone https://android.googlesource.com/platform/external/nanohttpd	
git clone https://android.googlesource.com/platform/external/nanopb-c	
git clone https://android.googlesource.com/platform/external/naver-fonts	
git clone https://android.googlesource.com/platform/external/netcat	
git clone https://android.googlesource.com/platform/external/netperf	
git clone https://android.googlesource.com/platform/external/neven	
git clone https://android.googlesource.com/platform/external/nfacct	
git clone https://android.googlesource.com/platform/external/nist-pkits	
git clone https://android.googlesource.com/platform/external/nist-sip	
git clone https://android.googlesource.com/platform/external/noto-fonts	
git clone https://android.googlesource.com/platform/external/oauth	
git clone https://android.googlesource.com/platform/external/objenesis	
git clone https://android.googlesource.com/platform/external/okhttp	
git clone https://android.googlesource.com/platform/external/opencore	#OpenCORE Media Framework
git clone https://android.googlesource.com/platform/external/opencv	
git clone https://android.googlesource.com/platform/external/openfst	
git clone https://android.googlesource.com/platform/external/openssh	
git clone https://android.googlesource.com/platform/external/openssl	
git clone https://android.googlesource.com/platform/external/open-vcdiff	
git clone https://android.googlesource.com/platform/external/openvpn	
git clone https://android.googlesource.com/platform/external/oprofile	
git clone https://android.googlesource.com/platform/external/owasp/sanitizer	
git clone https://android.googlesource.com/platform/external/pcre	
git clone https://android.googlesource.com/platform/external/pdfium	
git clone https://android.googlesource.com/platform/external/ping	
git clone https://android.googlesource.com/platform/external/ping6	
git clone https://android.googlesource.com/platform/external/pixman	
git clone https://android.googlesource.com/platform/external/ppp	
git clone https://android.googlesource.com/platform/external/proguard	
git clone https://android.googlesource.com/platform/external/protobuf	
git clone https://android.googlesource.com/platform/external/pthreads	
git clone https://android.googlesource.com/platform/external/qemu	
git clone https://android.googlesource.com/platform/external/qemu-android	
git clone https://android.googlesource.com/platform/external/qemu-pc-bios	
git clone https://android.googlesource.com/platform/external/qt	
git clone https://android.googlesource.com/platform/external/quake	
git clone https://android.googlesource.com/platform/external/regex-re2	
git clone https://android.googlesource.com/platform/external/replicaisland	
git clone https://android.googlesource.com/platform/external/robolectric	
git clone https://android.googlesource.com/platform/external/safe-iop	
git clone https://android.googlesource.com/platform/external/scrypt	
git clone https://android.googlesource.com/platform/external/selinux	
git clone https://android.googlesource.com/platform/external/sepolicy	
git clone https://android.googlesource.com/platform/external/sfntly	
git clone https://android.googlesource.com/platform/external/sil-fonts	
git clone https://android.googlesource.com/platform/external/skia	
git clone https://android.googlesource.com/platform/external/slf4j	
git clone https://android.googlesource.com/platform/external/smack	
git clone https://android.googlesource.com/platform/external/smali	
git clone https://android.googlesource.com/platform/external/sonic	
git clone https://android.googlesource.com/platform/external/sonivox	
git clone https://android.googlesource.com/platform/external/speex	
git clone https://android.googlesource.com/platform/external/sqlite	#SQLite database engine
git clone https://android.googlesource.com/(http://sqlite.org)
git clone https://android.googlesource.com/platform/external/squashfs-tools	
git clone https://android.googlesource.com/platform/external/srec	
git clone https://android.googlesource.com/platform/external/srtp	
git clone https://android.googlesource.com/platform/external/stlport	
git clone https://android.googlesource.com/platform/external/strace	
git clone https://android.googlesource.com/platform/external/stressapptest	
git clone https://android.googlesource.com/platform/external/svox	
git clone https://android.googlesource.com/platform/external/swig	
git clone https://android.googlesource.com/platform/external/syspatch	
git clone https://android.googlesource.com/platform/external/tagsoup	
git clone https://android.googlesource.com/platform/external/tcpdump	
git clone https://android.googlesource.com/platform/external/tesseract	#Tesseract Open Source OCR Engine
git clone https://android.googlesource.com/platform/external/timezonepicker-support	
git clone https://android.googlesource.com/platform/external/tinyalsa	
git clone https://android.googlesource.com/platform/external/tinycompress	
git clone https://android.googlesource.com/platform/external/tinyxml	
git clone https://android.googlesource.com/platform/external/tinyxml2	
git clone https://android.googlesource.com/platform/external/toy	
git clone https://android.googlesource.com/platform/external/toybox	
git clone https://android.googlesource.com/platform/external/tremolo	
git clone https://android.googlesource.com/platform/external/tremor	
git clone https://android.googlesource.com/platform/external/unicode	
git clone https://android.googlesource.com/platform/external/utf8proc	
git clone https://android.googlesource.com/platform/external/v8	
git clone https://android.googlesource.com/platform/external/valgrind	
git clone https://android.googlesource.com/platform/external/vixl	
git clone https://android.googlesource.com/platform/external/vogar	
git clone https://android.googlesource.com/platform/external/webkit	
git clone https://android.googlesource.com/platform/external/webp	
git clone https://android.googlesource.com/platform/external/webrtc	
git clone https://android.googlesource.com/platform/external/wpa_supplicant	
git clone https://android.googlesource.com/platform/external/wpa_supplicant_6	
git clone https://android.googlesource.com/platform/external/wpa_supplicant_8	
git clone https://android.googlesource.com/platform/external/xdelta3	
git clone https://android.googlesource.com/platform/external/xerces-cpp	
git clone https://android.googlesource.com/platform/external/xmlwriter	
git clone https://android.googlesource.com/platform/external/xmp_toolkit	
git clone https://android.googlesource.com/platform/external/yaffs2	
git clone https://android.googlesource.com/platform/external/zlib	
git clone https://android.googlesource.com/platform/external/zopfli	
git clone https://android.googlesource.com/platform/external/zxing	
git clone https://android.googlesource.com/platform/frameworks/av	
git clone https://android.googlesource.com/platform/frameworks/base	#Android framework classes and services
git clone https://android.googlesource.com/platform/frameworks/compile/libbcc	
git clone https://android.googlesource.com/platform/frameworks/compile/linkloader	
git clone https://android.googlesource.com/platform/frameworks/compile/llvm-ndk-cc	
git clone https://android.googlesource.com/platform/frameworks/compile/mclinker	
git clone https://android.googlesource.com/platform/frameworks/compile/slang	
git clone https://android.googlesource.com/platform/frameworks/ex	
git clone https://android.googlesource.com/platform/frameworks/media/libvideoeditor	
git clone https://android.googlesource.com/platform/frameworks/mff	
git clone https://android.googlesource.com/platform/frameworks/minikin	
git clone https://android.googlesource.com/platform/frameworks/ml	
git clone https://android.googlesource.com/platform/frameworks/multidex	
git clone https://android.googlesource.com/platform/frameworks/native	
git clone https://android.googlesource.com/platform/frameworks/opt/bitmap	
git clone https://android.googlesource.com/platform/frameworks/opt/bluetooth	
git clone https://android.googlesource.com/platform/frameworks/opt/calendar	
git clone https://android.googlesource.com/platform/frameworks/opt/carddav	#CardDAV library
git clone https://android.googlesource.com/platform/frameworks/opt/chips	
git clone https://android.googlesource.com/platform/frameworks/opt/colorpicker	
git clone https://android.googlesource.com/platform/frameworks/opt/com.google.android	
git clone https://android.googlesource.com/platform/frameworks/opt/com.google.android.googlelogin	
git clone https://android.googlesource.com/platform/frameworks/opt/datetimepicker	
git clone https://android.googlesource.com/platform/frameworks/opt/emoji	
git clone https://android.googlesource.com/platform/frameworks/opt/inputconnectioncommon	
git clone https://android.googlesource.com/platform/frameworks/opt/inputmethodcommon	
git clone https://android.googlesource.com/platform/frameworks/opt/mailcommon	
git clone https://android.googlesource.com/platform/frameworks/opt/mms	
git clone https://android.googlesource.com/platform/frameworks/opt/net/ethernet	
git clone https://android.googlesource.com/platform/frameworks/opt/net/ims	
git clone https://android.googlesource.com/platform/frameworks/opt/net/voip	
git clone https://android.googlesource.com/platform/frameworks/opt/net/wifi	
git clone https://android.googlesource.com/platform/frameworks/opt/photoviewer	
git clone https://android.googlesource.com/platform/frameworks/opt/setupwizard	
git clone https://android.googlesource.com/platform/frameworks/opt/telephony	
git clone https://android.googlesource.com/platform/frameworks/opt/timezonepicker	
git clone https://android.googlesource.com/platform/frameworks/opt/vcard	
git clone https://android.googlesource.com/platform/frameworks/opt/widget	
git clone https://android.googlesource.com/platform/frameworks/policies/base	
git clone https://android.googlesource.com/platform/frameworks/rs	
git clone https://android.googlesource.com/platform/frameworks/support	
git clone https://android.googlesource.com/platform/frameworks/testing	
git clone https://android.googlesource.com/platform/frameworks/uiautomator	
git clone https://android.googlesource.com/platform/frameworks/volley	
git clone https://android.googlesource.com/platform/frameworks/webview	
git clone https://android.googlesource.com/platform/frameworks/wilhelm	
git clone https://android.googlesource.com/platform/gdk	
git clone https://android.googlesource.com/platform/hardware/akm	
git clone https://android.googlesource.com/platform/hardware/broadcom/libbt	
git clone https://android.googlesource.com/platform/hardware/broadcom/wlan	
git clone https://android.googlesource.com/platform/hardware/google	
git clone https://android.googlesource.com/platform/hardware/intel/audio_media	
git clone https://android.googlesource.com/platform/hardware/intel/bootstub	
git clone https://android.googlesource.com/platform/hardware/intel/common/bd_prov	
git clone https://android.googlesource.com/platform/hardware/intel/common/libmix	
git clone https://android.googlesource.com/platform/hardware/intel/common/libstagefrighthw	
git clone https://android.googlesource.com/platform/hardware/intel/common/libva	
git clone https://android.googlesource.com/platform/hardware/intel/common/libwsbm	
git clone https://android.googlesource.com/platform/hardware/intel/common/omx-components	
git clone https://android.googlesource.com/platform/hardware/intel/common/utils	
git clone https://android.googlesource.com/platform/hardware/intel/common/wrs_omxil_core	
git clone https://android.googlesource.com/platform/hardware/intel/img/hwcomposer	
git clone https://android.googlesource.com/platform/hardware/intel/img/libdrm	
git clone https://android.googlesource.com/platform/hardware/intel/img/psb_headers	
git clone https://android.googlesource.com/platform/hardware/intel/img/psb_video	
git clone https://android.googlesource.com/platform/hardware/invensense	
git clone https://android.googlesource.com/platform/hardware/libhardware	#hardware abstraction library
git clone https://android.googlesource.com/platform/hardware/libhardware_legacy	
git clone https://android.googlesource.com/platform/hardware/msm7k	#msm7k hardware glue
git clone https://android.googlesource.com/platform/hardware/nvidia/audio	
git clone https://android.googlesource.com/platform/hardware/nvidia/tegra124	
git clone https://android.googlesource.com/platform/hardware/qcom/audio	
git clone https://android.googlesource.com/platform/hardware/qcom/bt	
git clone https://android.googlesource.com/platform/hardware/qcom/camera	
git clone https://android.googlesource.com/platform/hardware/qcom/display	
git clone https://android.googlesource.com/platform/hardware/qcom/gps	
git clone https://android.googlesource.com/platform/hardware/qcom/keymaster	
git clone https://android.googlesource.com/platform/hardware/qcom/media	
git clone https://android.googlesource.com/platform/hardware/qcom/msm8960	
git clone https://android.googlesource.com/platform/hardware/qcom/msm8x26	
git clone https://android.googlesource.com/platform/hardware/qcom/msm8x27	
git clone https://android.googlesource.com/platform/hardware/qcom/msm8x74	
git clone https://android.googlesource.com/platform/hardware/qcom/msm8x84	
git clone https://android.googlesource.com/platform/hardware/qcom/power	
git clone https://android.googlesource.com/platform/hardware/qcom/sensors	
git clone https://android.googlesource.com/platform/hardware/qcom/wlan	
git clone https://android.googlesource.com/platform/hardware/ril	#radio interface layer
git clone https://android.googlesource.com/platform/hardware/samsung_slsi/exynos5	
git clone https://android.googlesource.com/platform/hardware/ti/omap3	
git clone https://android.googlesource.com/platform/hardware/ti/omap4-aah	
git clone https://android.googlesource.com/platform/hardware/ti/omap4xxx	
git clone https://android.googlesource.com/platform/hardware/ti/wlan	
git clone https://android.googlesource.com/platform/hardware/ti/wpan	
git clone https://android.googlesource.com/platform/libcore	
git clone https://android.googlesource.com/platform/libcore2	
git clone https://android.googlesource.com/platform/libcore-snapshot	
git clone https://android.googlesource.com/platform/libnativehelper	
git clone https://android.googlesource.com/platform/manifest	#Android Platform Manifest
git clone https://android.googlesource.com/platform/motodev	
git clone https://android.googlesource.com/platform/ndk	
git clone https://android.googlesource.com/platform/packages/apps/AccountsAndSyncSettings	
git clone https://android.googlesource.com/platform/packages/apps/AlarmClock	
git clone https://android.googlesource.com/platform/packages/apps/BasicSmsReceiver	
git clone https://android.googlesource.com/platform/packages/apps/Bluetooth	
git clone https://android.googlesource.com/platform/packages/apps/Browser	
git clone https://android.googlesource.com/platform/packages/apps/Calculator	
git clone https://android.googlesource.com/platform/packages/apps/Calendar	
git clone https://android.googlesource.com/platform/packages/apps/Camera	
git clone https://android.googlesource.com/platform/packages/apps/Camera2	
git clone https://android.googlesource.com/platform/packages/apps/CellBroadcastReceiver	
git clone https://android.googlesource.com/platform/packages/apps/CertInstaller	
git clone https://android.googlesource.com/platform/packages/apps/Contacts	#UI for the Contacts, Call log, and Dialer applications
git clone https://android.googlesource.com/platform/packages/apps/ContactsCommon	
git clone https://android.googlesource.com/platform/packages/apps/DeskClock	
git clone https://android.googlesource.com/platform/packages/apps/Dialer	
git clone https://android.googlesource.com/platform/packages/apps/Email	
git clone https://android.googlesource.com/platform/packages/apps/Exchange	
git clone https://android.googlesource.com/platform/packages/apps/FMRadio	
git clone https://android.googlesource.com/platform/packages/apps/Gallery	
git clone https://android.googlesource.com/platform/packages/apps/Gallery2	
git clone https://android.googlesource.com/platform/packages/apps/Gallery3D	
git clone https://android.googlesource.com/platform/packages/apps/GlobalSearch	
git clone https://android.googlesource.com/platform/packages/apps/GoogleSearch	
git clone https://android.googlesource.com/platform/packages/apps/HTMLViewer	
git clone https://android.googlesource.com/platform/packages/apps/IM	
git clone https://android.googlesource.com/platform/packages/apps/InCallUI	
git clone https://android.googlesource.com/platform/packages/apps/KeyChain	
git clone https://android.googlesource.com/platform/packages/apps/Launcher	
git clone https://android.googlesource.com/platform/packages/apps/Launcher2	
git clone https://android.googlesource.com/platform/packages/apps/Launcher3	
git clone https://android.googlesource.com/platform/packages/apps/LegacyCamera	
git clone https://android.googlesource.com/platform/packages/apps/ManagedProvisioning	
git clone https://android.googlesource.com/platform/packages/apps/McLauncher	
git clone https://android.googlesource.com/platform/packages/apps/Mms	
git clone https://android.googlesource.com/platform/packages/apps/Music	
git clone https://android.googlesource.com/platform/packages/apps/MusicFX	
git clone https://android.googlesource.com/platform/packages/apps/Nfc	
git clone https://android.googlesource.com/platform/packages/apps/OneTimeInitializer	
git clone https://android.googlesource.com/platform/packages/apps/PackageInstaller	
git clone https://android.googlesource.com/platform/packages/apps/Phone	#Call management UI
git clone https://android.googlesource.com/platform/packages/apps/PhoneCommon	
git clone https://android.googlesource.com/platform/packages/apps/Protips	
git clone https://android.googlesource.com/platform/packages/apps/Provision	#Minimal
git clone https://android.googlesource.com/configuration/provisioning #app
git clone https://android.googlesource.com/platform/packages/apps/QuickSearchBox	
git clone https://android.googlesource.com/platform/packages/apps/Settings	
git clone https://android.googlesource.com/platform/packages/apps/SmartCardService	
git clone https://android.googlesource.com/platform/packages/apps/SoundRecorder	
git clone https://android.googlesource.com/platform/packages/apps/SpareParts	
git clone https://android.googlesource.com/platform/packages/apps/SpeechRecorder	
git clone https://android.googlesource.com/platform/packages/apps/Stk	
git clone https://android.googlesource.com/platform/packages/apps/Sync	
git clone https://android.googlesource.com/platform/packages/apps/Tag	
git clone https://android.googlesource.com/platform/packages/apps/Terminal	
git clone https://android.googlesource.com/platform/packages/apps/TvSettings	
git clone https://android.googlesource.com/platform/packages/apps/UnifiedEmail	
git clone https://android.googlesource.com/platform/packages/apps/Updater	
git clone https://android.googlesource.com/platform/packages/apps/VideoEditor	
git clone https://android.googlesource.com/platform/packages/apps/VoiceDialer	
git clone https://android.googlesource.com/platform/packages/experimental	
git clone https://android.googlesource.com/platform/packages/inputmethods/LatinIME	
git clone https://android.googlesource.com/platform/packages/inputmethods/OpenWnn	
git clone https://android.googlesource.com/platform/packages/inputmethods/PinyinIME	
git clone https://android.googlesource.com/platform/packages/providers/ApplicationsProvider	
git clone https://android.googlesource.com/platform/packages/providers/BookmarkProvider	
git clone https://android.googlesource.com/platform/packages/providers/CalendarProvider	#Content provider for calendar data
git clone https://android.googlesource.com/platform/packages/providers/ContactsProvider	#Content provider for call log data
git clone https://android.googlesource.com/platform/packages/providers/DownloadProvider	#Download Manager
git clone https://android.googlesource.com/platform/packages/providers/DrmProvider	
git clone https://android.googlesource.com/platform/packages/providers/GoogleContactsProvider
git clone https://android.googlesource.com/ContactsProvider #to sync contacts with Google
git clone https://android.googlesource.com/platform/packages/providers/GoogleSubscribedFeedsProvider	
git clone https://android.googlesource.com/platform/packages/providers/ImProvider	
git clone https://android.googlesource.com/platform/packages/providers/ManagementProvider	
git clone https://android.googlesource.com/platform/packages/providers/MediaProvider	
git clone https://android.googlesource.com/platform/packages/providers/PartnerBookmarksProvider	
git clone https://android.googlesource.com/platform/packages/providers/TelephonyProvider	
git clone https://android.googlesource.com/platform/packages/providers/TvProvider	
git clone https://android.googlesource.com/platform/packages/providers/UserDictionaryProvider	
git clone https://android.googlesource.com/platform/packages/providers/WebSearchProvider	
git clone https://android.googlesource.com/platform/packages/screensavers/Basic	
git clone https://android.googlesource.com/platform/packages/screensavers/PhotoTable	
git clone https://android.googlesource.com/platform/packages/screensavers/WebView	
git clone https://android.googlesource.com/platform/packages/services/EasService	
git clone https://android.googlesource.com/platform/packages/services/LockAndWipe	
git clone https://android.googlesource.com/platform/packages/services/Mms	
git clone https://android.googlesource.com/platform/packages/services/Telecomm	
git clone https://android.googlesource.com/platform/packages/services/Telephony	
git clone https://android.googlesource.com/platform/packages/wallpapers/Basic	
git clone https://android.googlesource.com/platform/packages/wallpapers/Galaxy4	
git clone https://android.googlesource.com/platform/packages/wallpapers/HoloSpiral	
git clone https://android.googlesource.com/platform/packages/wallpapers/LivePicker	
git clone https://android.googlesource.com/platform/packages/wallpapers/MagicSmoke	
git clone https://android.googlesource.com/platform/packages/wallpapers/MusicVisualization	
git clone https://android.googlesource.com/platform/packages/wallpapers/NoiseField	
git clone https://android.googlesource.com/platform/packages/wallpapers/PhaseBeam	
git clone https://android.googlesource.com/platform/pdk	
git clone https://android.googlesource.com/platform/prebuilt	#binaries to support linux and osx builds
git clone https://android.googlesource.com/platform/prebuilts/android-emulator	
git clone https://android.googlesource.com/platform/prebuilts/android-emulator-build/archive	
git clone https://android.googlesource.com/platform/prebuilts/android-emulator-build/mesa	
git clone https://android.googlesource.com/platform/prebuilts/android-emulator-build/mesa-deps	
git clone https://android.googlesource.com/platform/prebuilts/android-emulator-build/qemu-android-deps	
git clone https://android.googlesource.com/platform/prebuilts/clang/darwin-x86/3.1	
git clone https://android.googlesource.com/platform/prebuilts/clang/darwin-x86/3.2	
git clone https://android.googlesource.com/platform/prebuilts/clang/darwin-x86/arm/3.3	
git clone https://android.googlesource.com/platform/prebuilts/clang/darwin-x86/host/3.3	
git clone https://android.googlesource.com/platform/prebuilts/clang/darwin-x86/host/3.4	
git clone https://android.googlesource.com/platform/prebuilts/clang/darwin-x86/host/3.5	
git clone https://android.googlesource.com/platform/prebuilts/clang/darwin-x86/host/3.6	
git clone https://android.googlesource.com/platform/prebuilts/clang/darwin-x86/mips/3.3	
git clone https://android.googlesource.com/platform/prebuilts/clang/darwin-x86/sdk/3.5	
git clone https://android.googlesource.com/platform/prebuilts/clang/darwin-x86/x86/3.3	
git clone https://android.googlesource.com/platform/prebuilts/clang/linux-x86/3.1	
git clone https://android.googlesource.com/platform/prebuilts/clang/linux-x86/3.2	
git clone https://android.googlesource.com/platform/prebuilts/clang/linux-x86/arm/3.3	
git clone https://android.googlesource.com/platform/prebuilts/clang/linux-x86/host/3.3	
git clone https://android.googlesource.com/platform/prebuilts/clang/linux-x86/host/3.4	
git clone https://android.googlesource.com/platform/prebuilts/clang/linux-x86/host/3.5	
git clone https://android.googlesource.com/platform/prebuilts/clang/linux-x86/host/3.6	
git clone https://android.googlesource.com/platform/prebuilts/clang/linux-x86/mips/3.3	
git clone https://android.googlesource.com/platform/prebuilts/clang/linux-x86/x86/3.3	
git clone https://android.googlesource.com/platform/prebuilts/devtools	
git clone https://android.googlesource.com/platform/prebuilts/eclipse	
#Prebuilt packages from the Eclipse project, used to build components of the SDK.
git clone https://android.googlesource.com/platform/prebuilts/eclipse-build-deps	
git clone https://android.googlesource.com/platform/prebuilts/eclipse-build-deps-sources	
git clone https://android.googlesource.com/platform/prebuilts/fullsdk/build-tools/22-darwin	
git clone https://android.googlesource.com/platform/prebuilts/fullsdk/build-tools/22-linux	
git clone https://android.googlesource.com/platform/prebuilts/fullsdk/build-tools/22-windows	
git clone https://android.googlesource.com/platform/prebuilts/gcc/darwin-x86/aarch64/aarch64-linux-android-4.8	
git clone https://android.googlesource.com/platform/prebuilts/gcc/darwin-x86/aarch64/aarch64-linux-android-4.9	
git clone https://android.googlesource.com/platform/prebuilts/gcc/darwin-x86/arm/arm-eabi-4.6	
git clone https://android.googlesource.com/platform/prebuilts/gcc/darwin-x86/arm/arm-eabi-4.7	
git clone https://android.googlesource.com/platform/prebuilts/gcc/darwin-x86/arm/arm-eabi-4.8	
git clone https://android.googlesource.com/platform/prebuilts/gcc/darwin-x86/arm/arm-linux-androideabi-4.6	
git clone https://android.googlesource.com/platform/prebuilts/gcc/darwin-x86/arm/arm-linux-androideabi-4.7	
git clone https://android.googlesource.com/platform/prebuilts/gcc/darwin-x86/arm/arm-linux-androideabi-4.8	
git clone https://android.googlesource.com/platform/prebuilts/gcc/darwin-x86/arm/arm-linux-androideabi-4.9	
git clone https://android.googlesource.com/platform/prebuilts/gcc/darwin-x86/host/headers	
git clone https://android.googlesource.com/platform/prebuilts/gcc/darwin-x86/host/i686-apple-darwin-4.2.1	
git clone https://android.googlesource.com/platform/prebuilts/gcc/darwin-x86/mips/mips64el-linux-android-4.8	
git clone https://android.googlesource.com/platform/prebuilts/gcc/darwin-x86/mips/mips64el-linux-android-4.9	
git clone https://android.googlesource.com/platform/prebuilts/gcc/darwin-x86/mips/mipsel-linux-android-4.4.3
git clone https://android.googlesource.com/MIPS #4.4.3 toolchain, for 32-bit MacOS.
git clone https://android.googlesource.com/platform/prebuilts/gcc/darwin-x86/mips/mipsel-linux-android-4.6	
git clone https://android.googlesource.com/platform/prebuilts/gcc/darwin-x86/mips/mipsel-linux-android-4.7	
git clone https://android.googlesource.com/platform/prebuilts/gcc/darwin-x86/mips/mipsel-linux-android-4.8	
git clone https://android.googlesource.com/platform/prebuilts/gcc/darwin-x86/x86/i686-android-linux-4.4.3	
git clone https://android.googlesource.com/platform/prebuilts/gcc/darwin-x86/x86/i686-android-linux-4.6	
git clone https://android.googlesource.com/platform/prebuilts/gcc/darwin-x86/x86/i686-linux-android-4.6	
git clone https://android.googlesource.com/platform/prebuilts/gcc/darwin-x86/x86/i686-linux-android-4.7	
git clone https://android.googlesource.com/platform/prebuilts/gcc/darwin-x86/x86/x86_64-linux-android-4.7	
git clone https://android.googlesource.com/platform/prebuilts/gcc/darwin-x86/x86/x86_64-linux-android-4.8	
git clone https://android.googlesource.com/platform/prebuilts/gcc/darwin-x86/x86/x86_64-linux-android-4.9	
git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.8	
git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9	
git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-eabi-4.6	
git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-eabi-4.7	
git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-eabi-4.8	
git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.6	
git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.7	
git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.8	
git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9	
git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/host/i686-linux-glibc2.7-4.4.3	
git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/host/i686-linux-glibc2.7-4.6	
git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.11-4.6	
git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.11-4.8	
git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.15-4.8	
git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.7-4.6	
git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/host/x86_64-w64-mingw32-4.8	
git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/mips/mips64el-linux-android-4.8	
git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/mips/mips64el-linux-android-4.9	
git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/mips/mipsel-linux-android-4.4.3
git clone https://android.googlesource.com/MIPS #4.4.3 toolchain, for 32-bit linux.
git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/mips/mipsel-linux-android-4.6	
git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/mips/mipsel-linux-android-4.7	
git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/mips/mipsel-linux-android-4.8	
git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/x86/i686-android-linux-4.4.3	
git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/x86/i686-android-linux-4.6	
git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/x86/i686-linux-android-4.6	
git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/x86/i686-linux-android-4.7	
git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/x86/x86_64-linux-android-4.7	
git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/x86/x86_64-linux-android-4.8	
git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/x86/x86_64-linux-android-4.9	
git clone https://android.googlesource.com/platform/prebuilts/go/darwin-x86	
git clone https://android.googlesource.com/platform/prebuilts/go/linux-x86	
git clone https://android.googlesource.com/platform/prebuilts/go/windows-x86	
git clone https://android.googlesource.com/platform/prebuilts/gradle-plugin	
git clone https://android.googlesource.com/platform/prebuilts/libs/libedit	
git clone https://android.googlesource.com/platform/prebuilts/maven_repo/android	
git clone https://android.googlesource.com/platform/prebuilts/misc	#Miscellaneous prebuilt modules
git clone https://android.googlesource.com/platform/prebuilts/ndk	
git clone https://android.googlesource.com/platform/prebuilts/ninja/darwin-x86	
git clone https://android.googlesource.com/platform/prebuilts/ninja/linux-x86	
git clone https://android.googlesource.com/platform/prebuilts/python/darwin-x86/2.7.5	
git clone https://android.googlesource.com/platform/prebuilts/python/linux-x86/2.7.5	
git clone https://android.googlesource.com/platform/prebuilts/qemu-kernel	
git clone https://android.googlesource.com/platform/prebuilts/runtime	
git clone https://android.googlesource.com/platform/prebuilts/sdk	
git clone https://android.googlesource.com/platform/prebuilts/tools	
git clone https://android.googlesource.com/platform/sdk	#Development Tools for the SDK
git clone https://android.googlesource.com/platform/system/bluetooth	#bluetooth tools
git clone https://android.googlesource.com/platform/system/bt	
git clone https://android.googlesource.com/platform/system/core	#minimal bootable environment
git clone https://android.googlesource.com/platform/system/extras	#debugging/inspection tools
git clone https://android.googlesource.com/platform/system/gatekeeper	
git clone https://android.googlesource.com/platform/system/keyguard	
git clone https://android.googlesource.com/platform/system/keymaster	
git clone https://android.googlesource.com/platform/system/media	
git clone https://android.googlesource.com/platform/system/netd	
git clone https://android.googlesource.com/platform/system/security	
git clone https://android.googlesource.com/platform/system/vold	
git clone https://android.googlesource.com/platform/system/wlan/ti	#TI 1251 WLAN driver and tools
git clone https://android.googlesource.com/platform/tools/adt/eclipse	
git clone https://android.googlesource.com/platform/tools/adt/idea	
git clone https://android.googlesource.com/platform/tools/base	
git clone https://android.googlesource.com/platform/tools/build	
git clone https://android.googlesource.com/platform/tools/buildSrc	
git clone https://android.googlesource.com/platform/tools/emulator	
git clone https://android.googlesource.com/platform/tools/external/fat32lib	
git clone https://android.googlesource.com/platform/tools/external/go/src/github.com/go-gl/glfw	
git clone https://android.googlesource.com/platform/tools/external/go/src/github.com/go-gl-legacy/gl	
git clone https://android.googlesource.com/platform/tools/external/go/src/github.com/golang/protobuf	
git clone https://android.googlesource.com/platform/tools/external/go/src/golang.org/x/net	
git clone https://android.googlesource.com/platform/tools/external/go/src/golang.org/x/tools	
git clone https://android.googlesource.com/platform/tools/external/gradle	
git clone https://android.googlesource.com/platform/tools/gpu	
git clone https://android.googlesource.com/platform/tools/gradle	
git clone https://android.googlesource.com/platform/tools/idea	
git clone https://android.googlesource.com/platform/tools/loganalysis	
git clone https://android.googlesource.com/platform/tools/motodev	
git clone https://android.googlesource.com/platform/tools/studio/cloud	
git clone https://android.googlesource.com/platform/tools/studio/google/cloud/testing	
git clone https://android.googlesource.com/platform/tools/studio/google/cloud/tools	
git clone https://android.googlesource.com/platform/tools/studio/google/login	
git clone https://android.googlesource.com/platform/tools/studio/google/play	
git clone https://android.googlesource.com/platform/tools/studio/translation	
git clone https://android.googlesource.com/platform/tools/swt	
git clone https://android.googlesource.com/platform/tools/tradefederation	
git clone https://android.googlesource.com/platform/vendor/htc/dream-open	#build configuration for HTC Dream
git clone https://android.googlesource.com/platform/vendor/invensense	
git clone https://android.googlesource.com/platform/vendor/sample	
git clone https://android.googlesource.com/Platform-Chromium-Projects	#Parent projects for all projects with
git clone https://android.googlesource.com/Platform-Projects	#Base project for all active Android platform
git clone https://android.googlesource.com/Platform-Unrestricted-Projects	#Base project for Android platform
git clone https://android.googlesource.com/Public-Projects	
git clone https://android.googlesource.com/toolchain/avr-libc	
git clone https://android.googlesource.com/toolchain/benchmark	
git clone https://android.googlesource.com/toolchain/binutils	
git clone https://android.googlesource.com/toolchain/build	
git clone https://android.googlesource.com/toolchain/ccache	
git clone https://android.googlesource.com/toolchain/clang	
git clone https://android.googlesource.com/toolchain/cloog	
git clone https://android.googlesource.com/toolchain/compiler-rt	
git clone https://android.googlesource.com/toolchain/expat	
git clone https://android.googlesource.com/toolchain/gcc	
git clone https://android.googlesource.com/toolchain/gdb	
git clone https://android.googlesource.com/toolchain/gmp	
git clone https://android.googlesource.com/toolchain/gold	
git clone https://android.googlesource.com/toolchain/isl	
git clone https://android.googlesource.com/toolchain/jack	
git clone https://android.googlesource.com/toolchain/jill	
git clone https://android.googlesource.com/toolchain/llvm	
git clone https://android.googlesource.com/toolchain/manifest	
git clone https://android.googlesource.com/toolchain/mclinker	
git clone https://android.googlesource.com/toolchain/mpc	
git clone https://android.googlesource.com/toolchain/mpfr	
git clone https://android.googlesource.com/toolchain/perl	
git clone https://android.googlesource.com/toolchain/polly	
git clone https://android.googlesource.com/toolchain/ppl	
git clone https://android.googlesource.com/toolchain/python	
git clone https://android.googlesource.com/toolchain/valgrind	
git clone https://android.googlesource.com/toolchain/yasm	
git clone https://android.googlesource.com/tools/aospstats	#A project to collect and display stats about AOSP.
git clone https://android.googlesource.com/tools/repo
