# This is the master makefile for all the sub projects
#include Algorithms/Makefile
#include C/Makefile
#include CPP/Makefile
#include DataStructures/Makefile
include DesignPatterns/Makefile
#include Linux/Makefile

SRC = source
INC = include

.PHONY: clean
clean : 
	rm -f $(SRC)/*.o 
